version: "3.9"
services:

  postgres-db:
    image: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=postgres
    volumes:
    - type: volume
      source: postgres-data
      target: /var/lib/postgresql/data

  etl:
    build: python
    ports:
      - 8082:8082
    depends_on:
      - postgres-db
    restart: on-failure
  
  visualization:
    image: grafana/grafana
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - postgres-db
    volumes:
      - grafana-storage:/var/lib/grafana
    build:
      context: ./grafana 

volumes:
  postgres-data:
  grafana-storage: