{
 "title": "SAP PM Data Dashboard - Equipments and Functional Locations",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Equipment List",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Equipment\", \"Descript\" as \"Description\", \"Equicatgry\" as \"Category\", \"Maintplant\" as \"Maintenance Plant\", \"Planplant\" as \"Planning Plant\", \"Plangroup\" as \"Planning Group\"\nFROM equipment;\n"
    }
   ]
  },
  {
   "title": "Functional Locations",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Funcloc\" as \"Functional Location\", \"LabelSyst\" as \"Label\", \"Descript\" as \"Description\", \"Category\", \"Maintplant\" as \"Maintenance Plant\", \"Planplant\" as \"Planning Plant\", \"Plangroup\" as \"Planning Group\"\nFROM funcloc;\n"
    }
   ]
  },
  {
   "title": "Equipment per Maintenance Plant",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT count(\"Equipment\"), \"Maintplant\"\nFROM equipment\nGROUP BY \"Maintplant\""
    }
   ]
  },
  {
   "title": "Functional Locations per Maintenance Plant",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT count(\"Funcloc\"), \"Maintplant\"\nFROM funcloc\nGROUP BY \"Maintplant\""
    }
   ]
  },
  {
   "title": "% Equipment per Maintenance Plant",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(\"Equipment\"), \"Maintplant\"\nFROM equipment\nGROUP BY \"Maintplant\""
    }
   ]
  },
  {
   "title": "% Functional Locations per Maintenance Plant",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(\"Funcloc\"), \"Maintplant\"\nFROM funcloc\nGROUP BY \"Maintplant\""
    }
   ]
  }
 ]
}